- ui/locators.py
- ui/rhci.py
- ui/test_rhci.py
Contains RHCI/QCI code from the RHCI branch of robottelo.
Nothing works as is because we depended on the robottelo
framework to setup various things.   Future commits will
bring it back to a functional level.
> Initial commit

- .gitignore
This adds the .gitignore file offered by github.
> Adding Github's suggested .gitignore file

- pages/base.py
- pages/regions/header_menu.py
- pages/wizard.py
- plugin/navigation.py
- tests/test_login.py
This adds a few functions and enables navigation of the header menu.  This also implements the product selection page for the wizard.
> Fixing menu navigation and implementing product selection page

- pages/wizard/satellite/insights.py
This is still not finished as it does not return the next page when the Next button is clicked.   A library will be created to figure this out for any given page (i.e. what is the next object), and then this page object class will be updated.
Testing was only done through jupyter notebook.   So there may be other problems.   It's hopefully a good start though.
> Add satellite/insights page object class

- .gitignore
- pages/wizard/satellite/deployment_name.py
- pages/wizard/satellite/insights.py
- pages/wizard/satellite/update_availability.py
Have created deployment name page object, and update_availability page object.   Made sure that all of them including the insights page object could do back, and left comments on unfininshed functionality.
> Finish Satellite (or make a good start) with satellite page objects

- lib/api/fusor_api.py
fusor_api will now support toggling the deployment of cfme and ose
independently when creating a deployment
> Updating fusor_api to support OpenShift deployment

- pages/wizard/satellite/deployment_name.py
click_back() now returns the product selection page object.
> Make back button in deployment_name.py go to product selection

- pages/wizard/product_selection.py
> Add Next and Cancel buttons to product selection page object

- pages/wizard/regions/navigation_buttons.py
This will help manage and contain information for the wizards cancel, back, and next buttons and the additional buttons that come when you select cancel.   I have tested this, but I haven't hooked it in yet.   The next step will be to make it be contained by the Base class.   BTW, that is why this does not inherit from the Base class, because it must be contained by it, and I didn't want to have the circular dependency.
> Nav buttons

- pages/base.py
- pages/wizard/product_selection.py
- pages/wizard/regions/deployment_step_bar.py
- pages/wizard/regions/navigation_buttons.py
- pages/wizard/regions/task_step_bar.py
- pages/wizard/rhev/setup_type.py
- pages/wizard/satellite/deployment_name.py
- pages/wizard/satellite/insights.py
- pages/wizard/satellite/update_availability.py
Make it so the navigation buttons are auto navigated based on the vertical and horizontal task bars in the UI.
> Task step bar

- pages/deployments.py
- pages/page.py
- pages/wizard/product_selection.py
- tests/test_login.py
- tests/test_navigation.py
Adding deployments page, and some basic stuff to the product selection page. Also added a few utility methods to the page class to assist in testing.
> Adding product selection page and ajax wait methods

- docs/guides/pull_requests.rst
Changing the language of the PR policy, to remove any reference to the lgtm module.
> Updating documentation for PR policy

- pages/wizard/product_selection.py
Additionally I change API references to RHEV to RHV (keeping case).
> Add actions to product_select.py

- pages/wizard/regions/deployment_step_bar.py
- pages/wizard/regions/task_step_bar.py
- pages/wizard/subscriptions/add_subscriptions.py
- pages/wizard/subscriptions/content_provider.py
- pages/wizard/subscriptions/review_subscriptions.py
- pages/wizard/subscriptions/subscription_management.py
This adds the pages for Content Provider, Subscription Management Application, Add Subscriptions, and Review Subscriptions (which is currently just an empty class because there are no actionable elements on it).
> Content provider pages

- pages/wizard/rhev/hypervisor.py
- pages/wizard/rhev/storage.py
Adding storage for RHV self-hosted and new field for self-hosted engine hostname.
> Patch self-hosted: storage and engine hostname

- .gitignore
- lib/deployment_runner.py
- pages/base.py
- pages/page.py
- pages/wizard/product_selection.py
- pages/wizard/review/installation_review.py
- pages/wizard/subscriptions/subscription_management.py
- tests/test_deployment.py
- variables.yaml.example
This adds a deployment runner class that reads in a dictionary from a variables.yaml file (example file included) and supplies a set of methods to interact with corresponding page objects using the values from the supplied yaml file. Each method takes a page object as a parameter, fills out the page, and returns the next page object from the wizard. 
This should let us write deployment test cases that can determine a path through the wizard based on the page object class which is returned instead of checking the yaml data itself. For instance, if you are clicking next on the Access Insights page and wanted to check if you are on RHEV page:
```python
runner = UIDeploymentRunner()                                   
deployment_name_pg = runner.product_selection(new_deployment_pg) …
```
> Adding UIDeploymentRunner class and example variables.yaml

- lib/api/fusor_api.py
Updating fusor_api to latest version that was used for RH internal CI
jobs.
> Update the fusor_api to latest version

- lib/api/fusor_api.py
- tests/api/test_api_osp_deployment.py
- variables.yaml.example
This is a first pass at developing test for the Fusor  API.  This will use a [WIP] yaml file from blrm/deployment_runner branch and I'll be moving renaming the files in this PR over the next few days.  I'm open to any suggestions about the best place to store api tests.
> OSP api tests

- pages/wizard/rhv/storage.py
- tests/test_deployment.py
RHV deployment will now attempt to retry clicking next after 3 attempts
to mount the storage domains.  Sometimes QCI fails to mount the shares
properly but will succeed if retried
> Added retries for rhv storage mount failures

- pages/page.py
- pages/wizard/review/installation_progress.py
- pages/wizard/review/installation_review.py
- tests/test_deployment.py
- variables.yaml.example
Expanding elements coverage for the installation progress class to allow us to track the deployment status
> Query deployment progress

- conftest.py
- lib/api/fusor_api.py
- tests/api/test_api.py
- tests/api/test_api_osp_deployment.py
Add ability to monitor the progress of an OSP API deployment.
Add --deployment-name as a command line argument for pytest invocation
> API deployment progress

- tests/test_deployments_button_QCI93.py
- tests/test_new_deployment_button_QCI93.py
Super easy tests using already defined fixtures. Please comment on the names of the test files, their location, etc.
> tests for QCI-93

- tests/api/test_api_rhev_deployment.py
- variables.yaml.example
Add test for deploying RHV using the fusor api
> RHV api deployment test

- pages/wizard/product_selection.py
- tests/test_product_requirements_text_QCI97.py
I have couple of items here to discuss, see inline comments.
> test for qci-97

- lib/deployment_runner.py
- pages/page.py
- pages/qci_page.py
- pages/wizard/openstack/detect_undercloud.py
- pages/wizard/openstack/register_nodes.py
- pages/wizard/regions/deployment_step_bar.py
- requirements.txt
- tests/test_deployment.py
- variables.yaml.example
Code changes to allow for an automated GUI deploy of OSP using pytest.
> OSP GUI Deploy

- lib/deployment_runner.py
I forgot to commit it before I merged:
https://github.com/RedHatQE/fusor-qe/pull/70
> Remove autodetect de-selection.

- lib/deployment_runner.py
- tests/test_deployment.py
Add automation of the OpenShift pages to the deployment runner and test_deployment
> OCP webui automation

- pages/wizard/review/installation_progress.py
Adding properties and actions to the installation progress page to detect a content sync error element and add button clicks for different actions (Abandon, Delete, Redeploy)
> Content Sync error detection

- lib/deployment_runner.py
- pages/wizard/satellite/update_availability.py
- variables.yaml.example
Adds functionality around the 'after publishing' and new environment path.
> Deployment runner update

- lib/deployment_runner.py
- pages/wizard/openshift/nodes.py
- pages/wizard/product_selection.py
- variables.yaml.example
Updating OCP page to support new elements
> Update OCP node page elements

- lib/partial_deployment.py
This will be used by Deployment Page tests to create deployments that can then be used to test the functionality of the Deployment Page.   
https://projects.engineering.redhat.com/browse/RHCIQE-706
> Add createPartialDeployment() method

- pages/deployments.py
- tests/test_deployments_filters_QCI91.py
Adds test to test if the filter capability of the deployments page works.   I will in a different merge add the cleanup code (i.e. RHCIQE-573)
> RHCIQE  569
